In [2]:
import numpy as np

# print("2×2単位行列は")
print(np.eye(2))
# print("3×3単位行列は")
print(np.eye(3))
# print("4×4単位行列は")
print(np.eye(4))

2×2単位行列は
[[1. 0.]
 [0. 1.]]
3×3単位行列は
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4×4単位行列は
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
