In [1]:
import numpy as np

In [5]:
#basic array list
ex_list = [0, 1, 2, 3]
ex_list_np = np.array(ex_list)
print(ex_list)
#=>[0, 1, 2, 3]
print(ex_list_np)
#=>[0 1 2 3]

[0, 1, 2, 3]
[0 1 2 3]


In [8]:
# basic array
ex_array = np.array([1, 2, 3])
# multiple by basic array
multiple = 10 * ex_array
print(multiple)
#=>[10 20 30]

[10 20 30]


In [17]:
# use range
range_array = np.arange(10)
print(range_array)
#=>[0 1 2 3 4 5 6 7 8 9]
range_designation_array = np.arange(1, 10)
print(range_designation_array)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [22]:
# A two-dimensional array
# use ".reshape"
reshape_list = np.arange(12).reshape(3, 4)
print(reshape_list)
reshape_designation_array = np.arange(1, 13).reshape(3, 4)
print(reshape_designation_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
# Arithmetic progression
basic_array = np.arange(1, 10)
# each 2 skip in range(1~10)
aripro_array = basic_array[1 :10 :2]
print(aripro_array)
#=>[2 4 6 8]

[2 4 6 8]


In [36]:
basic_array = np.arange(8).reshape(4, 2)
# print(basic_array)
#=>[[0 1]
#=> [2 3]
#=> [4 5]
#=> [6 7]]
print(basic_array[:2])
#=>[[0 1]
#=> [2 3]]
print(basic_array[:2 :])
#=>[[0 1]
#=> [2 3]]
print(basic_array[:2, 1:3])
#=>[[1]
#=> [3]]

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[1]
 [3]]


In [46]:
# 'shape' is result of the array
print(basic_array[1:4].shape)
#=>(3, 2)

(3, 2)
